events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            # Удаляем все X-Forwarded-For от клиента
            proxy_set_header X-Forwarded-For "";
            
            # Устанавливаем правильный X-Forwarded-For начиная с IP клиента
            proxy_set_header X-Forwarded-For $remote_addr;
            
            # Проксируем на nginx2
            proxy_pass http://nginx2;
        }

        location /direct {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://app:5000;
        }

        location /chain1 {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://nginx2/chain1;
        }

        location /chain2 {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://nginx2/chain2;
        }
    }
}
