events {
    worker_connections 1024;
}

http {
    map $http_x_forwarded_for $xff {
        "" $remote_addr;
        default "$http_x_forwarded_for, $remote_addr";
    }

    server {
        listen 80;

        location / {
            proxy_set_header X-Forwarded-For $xff;
            proxy_pass http://nginx3;
        }

        location /chain1 {
            proxy_set_header X-Forwarded-For $xff;
            proxy_pass http://nginx3/chain1;
        }

        location /chain2 {
            proxy_set_header X-Forwarded-For $xff;
            proxy_pass http://app:5000;
        }
    }
}
